//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airlanes
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersView
    {
        public int ID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string User_Role { get; set; }
        public string Email_address { get; set; }
        public string Office { get; set; }
    }
}
